# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ping.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\nping.proto\"\x1f\n\x04Ping\x12\x17\n\x03uri\x18\x01 \x01(\x0e\x32\x04.URI:\x04PING*\x11\n\x03URI\x12\n\n\x04PING\x10\x80\x80\x04')
)

_URI = _descriptor.EnumDescriptor(
  name='URI',
  full_name='URI',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PING', index=0, number=65536,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=47,
  serialized_end=64,
)
_sym_db.RegisterEnumDescriptor(_URI)

URI = enum_type_wrapper.EnumTypeWrapper(_URI)
PING = 65536



_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='Ping.uri', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=65536,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=45,
)

_PING.fields_by_name['uri'].enum_type = _URI
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.enum_types_by_name['URI'] = _URI
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), dict(
  DESCRIPTOR = _PING,
  __module__ = 'ping_pb2'
  # @@protoc_insertion_point(class_scope:Ping)
  ))
_sym_db.RegisterMessage(Ping)


# @@protoc_insertion_point(module_scope)
